# hydra - фреймворк для управления файлами конфигурации, заточенный под ML-проекты.
defaults: 
  - _self_ #  значит "используй текущий файл как базовый конфиг"
  # отключает стандартные логи Hydra (чтобы не было лишнего мусора в консоли)
  - override hydra/hydra_logging: disabled  
  # используем свой логгер а не стандартный 
  - override hydra/job_logging: custom 

# настройки самой библиотеки Hydra
hydra:
  # Hydra обычно создаёт папки типа: outputs/2024-... а мы отключаем их 
  output_subdir: null
  # запускать всё в текущей папке (.)
  run: 
    dir: .

# ----------------------------------Pipeline-----------------------------
# настройки пайплайна обработки видео
pipeline:
  save_video: False  # сохранять ли итоговое видео, можем найти его на компе
  sent_info_db: True # отправлять ли данные в базу данных(если True → заранее должны работать микросервисы)


# -----------------------General---------------------------

general: 
  colors_of_roads: # in bgr
    1: [102, 204, 255] 
    2: [0, 0, 170]
    3: [17, 70, 10]
    4: [120, 56, 126]
    5: [30, 105, 215]
  buffer_analytics: 0.5 # считаем количество машин за последние 30 секунд
  min_time_life_track: 3 # минимальное количество секунд жизни трека, если обьект живет меньше 3 секунда то не учитываем. помогает убирать шум(ложные детекции)
  count_cars_buffer_frames: 25 # сглаживание - за сколько кадров считаем: за 25 кадров берем среднее число машин. а 25 кадров это примерно 1 секунда. 

# отвечает за источник видео
video_reader:
  src: test_videos/test_video.mp4
  # пропуск кадров по времени,  0 → читаем каждый кадр
  # 1 → 1 кадр в секунду
  skip_secs: 0
  # файл с кординатами дорог 
  # там у нас полигонами дан координаты полигон (polygon) из 4 точек "1": [
    # 1195.3, 361.5,
    # 1297.2, 310.7,
    # 1399.5, 315.2,
    # 1350.8, 380.2
# ] [x1, y1, x2, y2, x3, y3, x4, y4]
  roads_info: configs/entry_exit_lanes.json

# отвечает за обнаружение объектов (детекция)
detection_node: 
  # модель детектора 
  weight_pth: weights/yolov8m.pt 
  classes_to_detect: [2, 3, 5, 7] # то есть берем только транспорт 
  confidence: 0.10 
  iou: 0.7 # порог для NMS через Intersection over Union высокий (0.7) → оставляет больше боксов низкий (0.3) → сильнее чистит
  imgsz: 640 # размер изображения для модели

tracking_node: 
  # алгоритм: ByteTrack - он: связывает боксы между кадрами даёт ID каждому объекту
  # score >= first_track_thresh (0.5) используются чтобы: создать новый трек уверенно обновить существующий
  # 0.1 <= score < 0.5 - используются ТОЛЬКО чтобы: поддерживать уже существующий трек - но не создавать новый
  # но даже при создании новых треков, сначала сопоставляет предыдущий и текущий объект 
  # и если этот тот самый обьек то айди остается таким же 
  first_track_thresh: 0.5
  # порог для продолжения трека- даже слабые детекции (0.1) могут: поддерживать существующий трек - это ключевая идея ByteTrack
  # то есть если мы видим рядом боундинг боксы с увереностью больше 0.1 то мы с ними продолжаем трекать
  second_track_thresh: 0.10 
  # это порог для сопоставления (matching) объектов между кадрами в алгоритме ByteTrack
  # У тебя есть: прошлый кадр → треки (ID уже есть)
  # текущий кадр → новые detection нужно понять: "Этот бокс — это тот же объект или новый?"
  # если IoU ≥ match_thresh → считаем, что это тот же объект
  # "кадры идут очень быстро → объекты почти не двигаются → IoU высокий"
  match_thresh: 0.95 
  # сколько кадров "ждём" объект если объект пропал: не удаляем сразу - ждём 125 кадров
  # полезно если машина: закрылась другим объектом - временно исчезла
  track_buffer: 125

# отвечает за отображение видео и информации на экране
show_node: 
  # масштаб окна 1.0 → оригинальный размер 0.6 → уменьшение до 60%
  scale: 0.7
  # показывать ли видео True → будет окно (cv2.imshow) False → ничего не показываем
  imshow: True
  # окно усреднения FPS - считается FPS не мгновенно, а за последние 15 кадров
  fps_counter_N_frames_stat: 15
  # рисовать ли FPS на экране True → будет надпись типа:
  draw_fps_info: True 
  # показывать зоны (ROI) 📌 это те самые полигоны из твоего JSON дороги - линии въезда/выезда
  show_roi: True
  # заливка зон True → закрашенные области (полупрозрачные) False → только контуры
  overlay_transparent_mask: False 
  # True → только детекции (bbox от модели) False → полный pipeline (tracking + аналитика)
  show_only_yolo_detections: False 
  # цвет боксов True → каждый ID свой цвет 🎨 False → цвет по логике (например дорога / направление)
  show_track_id_different_colors: False 
  show_info_statistics: True # показывать статистику обычно справа от видео:

# отвечает за сохранение видео
video_saver_node:
  # FPS итогового видео - 
  fps: 24 
  out_folder: test_videos/output.mp4

# отвечает за отправку данных в базу данных
sent_info_db_node:
  # drop_table: True
  how_often_add_info: 5 # как часто писать в базу (в секундах) - значит: каждые 5 секунд → новая запись
  # имя таблицы в базе
  table_name: traffic_info
  # настройки подключения к базе данных PostgreSQL
  connection_info: 
    user: ${oc.env:POSTGRES_USER,user}
    password: ${oc.env:POSTGRES_PASSWORD,change_me}
    # где находится база localhost → на твоём компьютере IP → удалённый сервер docker → часто тоже localhost
    host: ${oc.env:APP_DB_HOST,localhost}
    port: ${oc.env:APP_DB_PORT,5488}
    database: ${oc.env:POSTGRES_DB,traffic_analyzer_db}










